components/Button/index.tsx
components/IconButton/index.tsx
styles/components/buttons.scss
styles/index.scss

- Adds Icon buttons
- Adds new button styles
- Makes IconButtons compatible with the new styling
---

feat: add icon buttons

---

components/Page/index.tsx
package.json
pages/index.tsx
styles/components/buttons.scss
styles/index.scss
styles/pages/index.scss
yarn.lock

feat: add homepage

---

components/Footer/index.tsx
components/index.ts
pages/_app.tsx
pages/index.tsx
styles/components/footer.scss
styles/components/navbar.scss
styles/index.scss
styles/pages/index.scss

feat: add footer

---

components/About/AboutCard.tsx
components/About/AboutList.tsx
components/About/AboutListItem.tsx
pages/about.tsx
styles/components/about.scss
styles/components/footer.scss
styles/components/navbar.scss
styles/index.scss
styles/pages/about.scss

Originally this was planned for the stats section however the name "stats" does not really match the idea of about cards. So instead I will add them to the about me page.
---

feat(About): add more information

---

components/PinnedRepos/PinnedRepoCard.tsx
components/PinnedRepos/PinnedRepoCardSkeleton.tsx
components/PinnedRepos/index.tsx
lib/types.ts
package.json
pages/stats.tsx
styles/components/pinnedrepo.scss
styles/index.scss
yarn.lock

feat: add stats page

---

components/WakaTimeStats/WakaTimeChart.tsx
components/WakaTimeStats/WakaTimeSkeleton.tsx
components/WakaTimeStats/index.tsx
lib/constants.ts
lib/types.ts
package.json
pages/api/wakatime.ts
pages/stats.tsx
styles/index.scss
styles/pages/stats.scss
yarn.lock

- Adds the missing WakaTime Stats
---

feat(Stats): add more information

---

lib/constants.ts
lib/games/tictactoe.ts
lib/types.ts
pages/404.tsx
styles/index.scss
styles/pages/404.scss

- Adds a 404 page
- Adds a TicTacToe game to the 404 page
- Adds an unbeatable AI
#4 
---

feat: add 404 page

---

components/Footer/index.tsx
styles/components/footer.scss

- Adds missing credits to footer
---

feat(Footer): add missing credits

---

components/Title/index.tsx
next.config.js
pages/404.tsx
pages/_app.tsx
pages/about.tsx
pages/index.tsx
pages/stats.tsx

- Adds missing meta tags
- Adds missing titles
- Adds missing redirect urls
---

feat: add missing meta data

---

components/About/AboutList.tsx
components/Title/index.tsx
components/WakaTimeStats/WakaTimeChart.tsx
config.json
pages/_app.tsx
pages/about.tsx
pages/api/anime.ts
pages/index.tsx
pages/stats.tsx

- Adds customisable options
---

feat: add customisable options

---

src/components/Layout.tsx
src/components/background/DarkMode.tsx
src/components/background/LightMode.tsx
src/pages/_app.tsx
src/pages/index.tsx
src/styles/globals.css
tailwind.config.js

- Adds a background
- Supports dark & light mode
- **PC VERSION ONLY, MOBILE VERSION NOT DESIGNED YET**
---

feat: add background with dark & light mode

---

src/components/Layout.tsx
src/components/background/DarkModeBlobs.tsx
src/components/background/LightModeBlobs.tsx
src/components/navbar/Menu.tsx
src/components/navbar/MenuButton.tsx
src/components/navbar/ThemeButton.tsx
src/components/navbar/index.tsx
src/pages/index.tsx
src/styles/globals.css
tailwind.config.js

- Adds a navbar
- Adds colour theme and other styles to tailwind
---

feat: add navbar

---

src/components/Cursor.tsx
src/lib/cursor.ts
src/pages/_app.tsx
src/styles/globals.css

feat: add custom cursor

---

src/components/Home/Landing.tsx
src/pages/index.tsx
tailwind.config.js

- Adds a welcome (landing) section to the home page
---

feat(Home): add landing section

---

src/components/Home/About.tsx
src/components/Home/Contact.tsx
src/components/Home/Projects.tsx
src/components/HomeSectionLayout.tsx
yarn.lock

- Cleans up copy-pasta code
- Creates components for frequently used code
---

chore: code clean-up

---

src/components/Home/About.tsx
src/components/Home/Contact.tsx
src/components/Home/Landing.tsx
tailwind.config.js

- fixes bug where button text is invis when light-theme is selected
---

fix: invisible buttons with light-theme enabled

---

src/components/Home/Landing.tsx
src/components/Home/ProjectCard.tsx
src/components/HomeSectionLayout.tsx
src/components/animations/Landing.ts
src/components/animations/Navbar.ts
src/components/animations/general.ts
src/components/footer/GitHubStats.tsx
src/components/navbar/MenuButton.tsx
src/components/navbar/ThemeButton.tsx
src/components/navbar/index.tsx
src/styles/globals.css

- Adds a transition animation
- Navbar animation
- Section pop-up animation
---

feat: add animations

---

package.json
src/components/Home/Landing.tsx
src/components/HomeSectionLayout.tsx
src/pages/_app.tsx
src/styles/globals.css
yarn.lock

- Adds a loading progress bar
- Adds page transition
---

feat: add loading animations

---

src/lib/constants.ts
src/lib/games/tictactoe.ts
src/lib/types.ts
src/pages/_error.tsx

- Adds error page with TicTacToe game
- Adds TicTacToe AI
---

feat: add error page

---

src/components/HeadTitle.tsx
src/components/Home/About.tsx
src/lib/utils.ts
src/pages/_app.tsx
src/pages/_error.tsx
src/pages/anime.tsx
src/pages/index.tsx

feat: add meta-data

---

packages/buttons/package.json
packages/buttons/src/Button.tsx
packages/buttons/src/arrow/Arrow.tsx
packages/buttons/src/arrow/BlackButtonArrow.tsx
packages/buttons/src/arrow/PrimaryButtonArrow.tsx
packages/buttons/src/arrow/index.ts
packages/buttons/src/index.tsx
packages/buttons/src/styled/BlackButton.tsx
packages/buttons/src/styled/PrimaryButton.tsx
packages/buttons/src/styled/index.ts
packages/buttons/src/types.ts
packages/buttons/tsconfig.eslint.json
packages/buttons/tsconfig.json
yarn.lock

feat: add buttons

---

apps/web/package.json
apps/web/src/pages/index.tsx
packages/markdown/package.json
packages/markdown/src/index.tsx
packages/markdown/tsconfig.eslint.json
packages/markdown/tsconfig.json
packages/ui/package.json
packages/ui/src/Home/EmojiBulletPoint.tsx
yarn.lock

feat: add markdown

---

apps/web/src/pages/index.tsx
packages/constants/src/Animations/index.ts
packages/constants/src/Navbar/animations.ts
packages/constants/src/index.ts
packages/navbar/src/buttons/MenuButton.tsx
packages/ui/package.json
packages/ui/src/Animations/SlideFade.tsx
packages/ui/src/Animations/index.ts
packages/ui/src/index.tsx
yarn.lock

feat(Landing): add animations

---

apps/web/next.config.mjs
apps/web/src/pages/_document.tsx
apps/web/src/pages/index.tsx
packages/constants/src/Projects/index.ts
packages/constants/src/index.ts
packages/ui/src/Projects/ProjectCard.tsx
packages/ui/src/Projects/index.ts
packages/ui/src/index.tsx
packages/ui/src/layout/PageLayout.tsx

feat(Home): add projects section

---

apps/web/package.json
apps/web/src/lib/email.ts
apps/web/src/pages/_app.tsx
apps/web/src/pages/index.tsx
packages/buttons/src/styled/PrimaryButton.tsx
packages/constants/src/Home/index.ts
packages/ui/package.json
packages/ui/src/Fonts.ts
packages/ui/src/Home/ContactForm.tsx
packages/ui/src/Home/Experience.tsx
packages/ui/src/Home/index.ts
packages/ui/src/Projects/ProjectCard.tsx
packages/ui/src/index.tsx
yarn.lock

feat(Home): add contact form

---

apps/web/next-seo.config.ts
apps/web/next-sitemap.config.cjs
apps/web/next.config.mjs
apps/web/package.json
apps/web/src/pages/_app.tsx
yarn.lock

feat: add seo

---

apps/web/package.json
apps/web/src/pages/projects.tsx
packages/ui/src/Projects/ProjectCard.tsx
yarn.lock

feat: add projects

---

apps/web/package.json
apps/web/src/pages/_app.tsx
apps/web/src/pages/anime.tsx
packages/constants/src/Anime/index.ts
packages/constants/src/Modal/index.ts
packages/constants/src/index.ts
packages/modal/package.json
packages/modal/src/BackDrop.tsx
packages/modal/src/ModalItem.tsx
packages/modal/src/index.tsx
packages/modal/tsconfig.eslint.json
packages/modal/tsconfig.json
packages/ui/package.json
packages/ui/src/Anime/AnimeCard.tsx
packages/ui/src/Anime/AnimeModal.tsx
packages/ui/src/Anime/index.ts
packages/ui/src/Fonts.ts
packages/ui/src/index.tsx
yarn.lock

feat: add anime list

---

apps/web/package.json
apps/web/src/pages/_app.tsx
packages/firebase/src/hooks/AppCheck.tsx
yarn.lock

chore(deps): add analytics
